[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['echo "This is a monorepo. Deploy frontend and backend separately."']

[phases.build]
cmds = ['echo "Please deploy from /fronddesk for frontend or /backend for backend"']

[start]
cmd = 'echo "Deploy frontend from /fronddesk or backend from /backend directory"'
